### ISSUE TITLE
Lists are now empty

### ISSUE THREAD

**Issue by solracsf** [borestad/blocklist-ip#4]
Something look wrong on the CI as all lists are now empty since https://github.com/borestad/blocklist-ip/commit/163d2825801fab4b59f581d9562d4fbdc0245762 🤔

**Comment by solracsf** [comment]
Hi @borestad is this project dead? Without CI working correctly, this repo is useless...

Thanks 👍🙏

**Comment by borestad** [comment]
No, not dead at all! Damn...a bug in the CI made all lights turn green 😢. It's been updated now and working now.
I have another private repository that's more "fooproof" + more statistics that I've been running separate for a while.

Thank you for reporting!

**Comment by borestad** [comment]
@solracsf @iJorgen 
The repository have now been upgraded to my experimental branch which is faster in ci/smaller in gitsize / more reliable & contains historic data 🙃
